### ISSUE TITLE
Fleshrender's Hook trinket not showing for Warlocks from Iron Docks

### ISSUE THREAD

**Issue by hmniw** [teelolws/ShadowlandsSeason4EncounterJournal#10]
Fleshrender's Hook shows as a drop in the wowhead article and I got in on my lock in week 1, but isn't show in S4 dungeon journal. Not sure if it drops from Grimrail, assuming it doesn't, but idk, but defo drops from Docks for int users.

**Comment by teelolws** [comment]
There is a bug making Grimrail loot show under Iron Docks. Pushing a fix now.
