### ISSUE TITLE
Have to re-select season 4 on the drop down menu everytime

### ISSUE THREAD

**Issue by billyqu** [teelolws/ShadowlandsSeason4EncounterJournal#5]
Everytime i opened up the encounter journal, i have to re-select season 4 from the drop down menu. Is it possible to make it stay in season 4 when i open the enounter journal?

**Comment by teelolws** [comment]
Not without changing Blizzards code, and I'm trying to avoid that.

**Comment by Culistrex** [comment]
I don't understand completely. So when I open the Season 4 from the dropdown and looks at the items, they are all ilvl 50+. Is this intended?

**Comment by teelolws** [comment]
> I don't understand completely. So when I open the Season 4 from the dropdown and looks at the items, they are all ilvl 50+. Is this intended?

I can't change the items you see. Theres no simple function like "show me this item if it was ilvl285 instead". Gotta hope Blizzard does that. At least seeing an ilvl50 version in Grimrail Depot gives you an idea of what stats it will have if it drops for you.

**Comment by Culistrex** [comment]
> > I don't understand completely. So when I open the Season 4 from the dropdown and looks at the items, they are all ilvl 50+. Is this intended?
> 
> I can't change the items you see. Theres no simple function like "show me this item if it was ilvl285 instead". Gotta hope Blizzard does that. At least seeing an ilvl50 version in Grimrail Depot gives you an idea of what stats it will have if it drops for you.

Yeah. I don't know about any of this stuff. Thank you for replying

**Comment by teelolws** [comment]
I've just pushed a patch that *might* scale the items up to ilvl 285. Or it might only work for me. Can you confirm if it works?

![image](https://user-images.githubusercontent.com/49792789/183778307-77ae9a18-de8e-4b15-99f6-e7c3607e1cec.png)

**Comment by Culistrex** [comment]
> I've just pushed a patch that _might_ scale the items up to ilvl 285. Or it might only work for me. Can you confirm if it works?
> 
> ![image](https://user-images.githubusercontent.com/49792789/183778307-77ae9a18-de8e-4b15-99f6-e7c3607e1cec.png)

It seems so
![image](https://user-images.githubusercontent.com/110877797/183819064-ef7739f6-7d95-45e2-a89b-e5035a093c89.png)
