### ISSUE TITLE
Loot table problem

### ISSUE THREAD

**Issue by Khato44** [teelolws/ShadowlandsSeason4EncounterJournal#9]
Hi ! I was trying to target some pieces of gear and when I used the dropdown menu to select a piece, let's say the neck piece, i could see the neck pieces of all dungeons but the WOD ones, and when I clicked on the WOD ones, it "froze" the window, couldn't click back to the previous menu 

I can try to find something to record the problem if needed

**Comment by teelolws** [comment]
Let me know if you still have problems after todays patch.
